# Generated by Django 4.0.5 on 2022-12-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocktestquestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mocktestquestion',
            name='subject_id',
        ),
    ]
