# Generated by Django 4.0.5 on 2022-12-31 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('mocktestquestion', '0002_remove_mocktestquestion_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktestquestion',
            name='subject_id',
            field=models.ForeignKey(default=2.2, on_delete=django.db.models.deletion.CASCADE, to='subject.subject'),
            preserve_default=False,
        ),
    ]
