# Generated by Django 4.0.5 on 2023-01-10 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocktestquestion', '0003_mocktestquestion_subject_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mocktestquestion',
            old_name='mock_test_id',
            new_name='mock_test',
        ),
        migrations.RenameField(
            model_name='mocktestquestion',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
