# Generated by Django 3.1 on 2022-12-26 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mocktestquestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTestOption',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=50)),
                ('is_correct', models.BooleanField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktestquestion.mocktestquestion')),
            ],
        ),
    ]
