# Generated by Django 4.0.5 on 2023-01-10 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocktestoption', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mocktestoption',
            old_name='question_id',
            new_name='question',
        ),
    ]
