# Generated by Django 3.1 on 2023-01-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file_field',
            field=models.FileField(blank=True, upload_to='note'),
        ),
    ]
